version: '3'
services:
  database:
    image: mysql
    container_name: mysql-container
    restart: always
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tongue
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - /etc/mysql/my.cnf
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network2

  application:
    build: .
    container_name: demo3
    ports:
      - "3050:8080"
    depends_on:
      - database
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/tongue?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - test_network2

networks:
  test_network2: